FROM python:3.9-slim

WORKDIR /app

# Copy the shared requirements file from root
COPY requirements_streamlit.txt ./requirements.txt
RUN pip install --default-timeout=600 --no-cache-dir -r requirements.txt

# Copy only Streamlit code
COPY streamlit/app_streamlit.py .

EXPOSE 8501

CMD ["streamlit", "run", "app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
